/**
 * Product Entity
 *
 * A physical item managed in inventory. Tracks SKU, pricing,
 * quantity, and lifecycle status. Belongs to a Warehouse.
 *
 * AI Capabilities:
 *   - product.describe: Auto-generates a marketing description on create.
 *     Triggered by the on_create event. Falls back to empty string if AI unavailable.
 */

import { defineEntity, defineAICapability } from "@metasaas/contracts";
import { z } from "zod";

/**
 * AI Capability: Auto-generate a product description from name, category, and price.
 * Fires automatically when a product is created (on_create trigger).
 * If AI is unavailable, the description field remains empty (graceful degradation).
 */
const describeProduct = defineAICapability({
  id: "product.describe",
  type: "generation",
  intent:
    "Generate a concise, professional product description (1-2 sentences) suitable for an inventory catalog. Mention the product category and any notable attributes.",
  input: {
    contextFields: ["name", "category", "price"],
  },
  output: {
    schema: z.object({
      description: z.string().max(500),
    }),
    fallback: { description: "" },
  },
  trigger: "on_create",
  preferences: {
    quality: "fast",
  },
});

export const ProductEntity = defineEntity({
  name: "Product",
  pluralName: "Products",
  description:
    "A physical inventory item with SKU, pricing, and stock levels. Stored in a warehouse and tracked through a lifecycle.",

  fields: [
    {
      name: "name",
      type: "text",
      required: true,
      description: "Product display name (e.g., 'Wireless Keyboard')",
    },
    {
      name: "sku",
      type: "text",
      required: true,
      description: "Stock Keeping Unit — unique identifier for inventory tracking",
    },
    {
      name: "description",
      type: "rich_text",
      required: false,
      description: "Product description for catalog display. Auto-generated by AI if left empty.",
    },
    {
      name: "category",
      type: "enum",
      required: true,
      options: ["electronics", "furniture", "clothing", "food", "raw_materials", "other"],
      defaultValue: "other",
      description: "Product category for classification and filtering",
    },
    {
      name: "status",
      type: "enum",
      required: true,
      options: ["draft", "active", "discontinued"],
      defaultValue: "draft",
      description: "Lifecycle status of the product",
    },
    {
      name: "price",
      type: "currency",
      required: false,
      description: "Unit selling price in the base currency",
    },
    {
      name: "quantity",
      type: "number",
      required: false,
      description: "Current quantity on hand in the warehouse",
    },
    {
      name: "reorderLevel",
      type: "number",
      required: false,
      description: "Quantity threshold below which restocking is needed",
    },
  ],

  relationships: [
    {
      type: "belongsTo",
      entity: "Warehouse",
      foreignKey: "warehouse_id",
    },
  ],

  workflows: [
    {
      name: "productLifecycle",
      field: "status",
      transitions: [
        { from: "draft", to: "active" },
        { from: "active", to: "discontinued", triggers: ["notify_team"] },
        { from: "active", to: "draft" },
      ],
    },
  ],

  aiCapabilities: [describeProduct],

  ui: {
    icon: "package",
    listColumns: ["name", "sku", "status", "category", "quantity"],
    searchFields: ["name", "sku", "description"],
    defaultSort: { field: "name", direction: "asc" },
    defaultView: "kanban",
    kanban: { groupBy: "status" },
  },
});
